plugins:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4.4
  NewCops: enable
  Exclude:
    - db/migrate/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false