default: &default
  encoding: unicode
  url: <%= ENV.fetch("BANK_DATABASE_URL") %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bank_development

test:
  <<: *default
  database: bank_test

production:
  <<: *default
  database: bank_production
